### ISSUE TITLE
tensorflow_OD_API_Inference_Example

### ISSUE THREAD

**Issue by sjmin99** [xown3197/JetsonNano-ROS2#1]
1. 먼저 공식 API documentation([링크](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/2.2.0/install.html#tensorflow-object-detection-api-installation))을 참고해서 필요한 패키지를 설치할 것.
![image](https://user-images.githubusercontent.com/50588004/202184308-1aed8441-c891-4d74-aad0-6c7fa4200c2c.png)
위에 그림 단계까지만 수행하여 conflict가 발생하기 전까지 라이브러리를 설치하면 되지만, 만약 코드 실행시에 필요한 라이브러리가 있으면 요령껏 따로 설치.(추후 수정 예정)

2. 1번 과정에서 documentation을 참고해서 진행했다면 터미널 현재 경로가 아래와 같을 것임.
`<Local_PATH>/Tensorflow\models\research`
해당 경로에 있다면 제공된 파일을 저장해서 현재 경로에 압축을 해제할 것.[inference_code.zip](https://github.com/xown3197/JetsonNano-ROS2/files/10021723/inference_code.zip)

3. tar파일로 압축된 ckpt 폴더까지 압축을 해제했다면 아래 명령어를 통해 inference 가능.
`python3 inference.py --ckpt_path <LOCAL_PATH>/content/tmp3`

4. 모델이 동작하는지 가능성만 본거라서 검출 결과 labeling을 올바르게 표현 안했는데 아무튼 정상 동작을 했다는 가정하에 현재 경로에 "debug.jpg"라는 이미지 파일이 생성되며 다음과 같이 검출 결과가 함께 나오면 정상.
![image](https://user-images.githubusercontent.com/50588004/202185465-d5d103ad-ddac-45c6-ab41-c0525b721ee9.png)

**Comment by xown3197** [comment]
확인
